version: '3.8' # version of docker-compose

services: # services that will be run
  web: 
    build:
      context: ./web 
    ports:
       - "4350:80"
    networks:
      - sharedDockNet
  
  be:
    build: # build the image from the current directory
      context: ./BE
    ports:
      - "1234:5000"
    networks:
      - sharedDockNet

networks: # network name
  sharedDockNet: 
