# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the custom Nginx configuration file into the container
COPY HomePage.html /usr/share/nginx/html/index.html
COPY css /usr/share/nginx/html/css